dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-02/run.sh |
  bash
notifications:
  slack:
    secure: uD/T2Ot1xF8prRdHEu2QWp0VFzzJYMJgeWZZn4P5jCASAsShdUWz04a8KVmQRGprLN72FsHo5oxrsAYEhrwo4KulvdWOaSIH8wnHx++HtybRrZ4kxfSew/4Nv+RPGN9zE1eM5hv1Xwb7d8EXfxdCP8PLkZyl/Jp+NoEtllBT8tij1bNBinOlv7zUBM5Fc/jXLC8AqOsRGSUgJVPF+D9TuYHT40HPRHFBjiJcEHShFmbR5ODE6j0zCjkaHEf24myqhdJQY33u3f/E8BmFXLa9B9EuAxexqesA7/SGSLBc+sj34+zxNmlEtfWy81D2v9Kdfj+DaqjK+Yo+kUv1c50O+9v3hFXqQGypjoAfCzZWz36la9Y7OBXb/pK5Vz9BSicBhUlLd1l0DGPs+3Md+F31C3wLyyW/y1rOPWKaARr1L4ouUZ1yun/doBPNp/zaLlbyFI+7DHsoeZigzCFReusQKBgAOJOHLGS6pzjXgxZ6KFxtjDiw/C/DJLuC6FG5Z+3xnw8bPIONDUJw4VqsSRQIkHA8og9B6RfL5IrMl7P++gGKxBTBtLFeg/AqVhLfn/2Yg74DifolupfwI2RQK9hVrglvVFKz4D7YAc1P2XDIKjrKZQc2iXLpbv/XA+WQNBUVUT7goH/9cYEG/TLwaiGijPnvaQ34Yg365Gnshsm181k=
